export const COUNTER_INCREMENT = 'COUNTER_INCREMENT';
export const COUNTER_DECREMENT = 'COUNTER_DECREMENT';
export const COUNTER_INCREMENT_WITH_VALUE = 'COUNTER_INCREMENT_WITH_VALUE';
export const COUNTER_DECREMENT_WITH_VALUE = 'COUNTER_DECREMENT_WITH_VALUE';
